"""initial schema: pgvector extension, core tables, HNSW memory index

Revision ID: 0001_initial
Revises:
Create Date: 2026-01-15 00:00:00.000000

This baseline migration first enables the ``vector`` extension (required by the
``memory_records.embedding`` column and its HNSW index) and then materialises
the full schema from the SQLAlchemy metadata. Building from metadata guarantees
the initial database matches the ORM models exactly; subsequent schema changes
use autogenerated, hand-reviewed migrations.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from app.db.session import Base
import app.models  # noqa: F401  (registers all tables on Base.metadata)

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    # pgvector must exist before any table referencing the Vector type.
    bind.execute(sa.text("CREATE EXTENSION IF NOT EXISTS vector"))
    # Create every table, constraint, and index defined on the models,
    # including the HNSW index on memory_records.embedding.
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
    bind.execute(sa.text("DROP EXTENSION IF EXISTS vector"))
